### PR TITLE
Updates for wiki-pages

### PR DESCRIPTION
**Pull request by couven92**
## Changes for main repo

* Changes wiki-pages into proper git submodule instead of duplicating auto-generated assets.
* Dockerfile set up to auto-generate HTML assets from wiki markdown pages on image build

## Changes in wiki

* Corrected markdown links, removed obsolete artifacts from previous pages that re no longer needed
* Renamed wiki pages that include norwegian characters. Both the go server and GitHub are able to handle encoded URLs paths. Improves headings of these wiki pages (sine the Title Level-1 heading is inferred from filename)
* Merge 80-chars-a-line line breaks to single long lines. prevents HTML from having forced <br> tags which improves readability of wiki-pages on large screens.
* Updates to debugging guide

**UPDATE** Appropiate guides on the wiki-pages include autogenerated helplinks.

### CODE REVIEW

**Comment by couven92** [comment]
Fixes https://github.com/skolelab/airbit/issues/9
Fixes https://github.com/skolelab/airbit/issues/11
Fixes https://github.com/skolelab/airbit/issues/7

**Comment by couven92** [comment]
Add updated markdown pages, guides now include help-link at appropiate headers.

Fixes https://github.com/skolelab/airbit/issues/10

**Comment by couven92** [comment]
@fjukstad Alternatively, if you think that a submodule is too cumbersome, we could dissolve the wiki on https://github.com/skolelab/airbit/wiki and move all the contents into a folder in this repo instead... Since we host the wiki on http://airbit.uit.no anyways, we might not have any need for the GitHub-wiki?

Just a thought, what do you think?

**Comment by couven92** [comment]
Changes to code examples for the dust sensor and GPS have been added to the wiki (ref.: https://github.com/skolelab/airbit/issues/12)

Debugging guide now includes section about usage of variables outside of scope.

**Comment by fjukstad** [comment]
Looks good. The building the docker container fails however: 
```
[bfj001@... luft]$ docker build -t luft .
Sending build context to Docker daemon  69.09MB
Step 1/17 : FROM node AS wiki-gen
 ---> c888d933885c
Step 2/17 : ADD wiki /wiki
 ---> Using cache
 ---> d3c3658abf3f
Step 3/17 : WORKDIR /wiki
 ---> Using cache
 ---> f20eb3d254f1
Step 4/17 : RUN ["npm", "install"]
 ---> Using cache
 ---> ad5a1ed51ae9
Step 5/17 : RUN ["node", "airbit.wiki.js"]
 ---> Running in 992825d5e5ee
module.js:557
    throw err;
    ^

Error: Cannot find module '/wiki/airbit.wiki.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
The command 'node airbit.wiki.js' returned a non-zero code: 1

```

**Comment by couven92** [comment]
@fjukstad Oh... Hmm, okay seems that Docker dislikes git submodules... I'll just carry over the wiki repo and integrate it here (makes it simpler anyways)

**Comment by couven92** [comment]
@fjukstad ref.: #13

**Comment by fjukstad** [comment]
Great stuff @couven92  👍

**Pull request merged**
