### PR TITLE
Edit homepage text and add logo

### PR DESCRIPTION
**Pull request by couven92**
Changed the homepage text:

* corrected spelling errors
* add air:bit logo
* link to Wiki-pages (incl. dedicated direct link to Guides wiki-page)

### CODE REVIEW

**Comment by fjukstad** [comment]
Nice! Could you make the cloud centered and above the text? Something like the image below. Thanks! 

img_8831

**Comment by couven92** [comment]
@fjukstad like this? (c6a96aa) Also coloured the logo in the navbar colours for good measure :)

**Comment by fjukstad** [comment]
👏  Yeah! 👍

**Comment by couven92** [comment]
Big thanks to @pwntus for helping me put with the CSS stuff here :)

**Pull request merged**
