### PR TITLE
Wiki update

### PR DESCRIPTION
**Pull request by couven92**
* Spelling corrections
* Added information on units for dust sensor
* Clarify why the pin numbers for the `RX` and `TX` lines to the GPS need to be mirrored in respect to the pinout

### CODE REVIEW

**Comment by couven92** [comment]
@fjukstad (sorry, I forgot to include this in the earlier PR... Soon we have to write a CI/CD script, so that you don't have to manually deply everytime :P )

**Comment by couven92** [comment]
@fjukstad Oh, appearently I have reordered the columns in the dataformat. Uh, what is the correct ordering? Or where is the code that handles the data?

**Comment by fjukstad** [comment]
The correct format is ` timestamp, latitude, longitude, pm10, pm2.5, humidity, temperature`.

**Comment by couven92** [comment]
@fjukstad Please have a closer look at https://github.com/fjukstad/luft/pull/19/commits/1c80a88f6ccd249d9247d774cede16628f323f17 I think I found an error that would lead to Latitude/Longitude being switched.

**Comment by fjukstad** [comment]
We might want to get @ninaangelvik to look at 1c80a88.

**Comment by couven92** [comment]
@fjukstad ready to merge 👍

**Comment by couven92** [comment]
**UPDATE:** include fix for #20

**Comment by fjukstad** [comment]
:+1:

**Pull request merged**
